/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.statistical_estimation;
import java.util.*;
import javax.swing.*;
import java.text.DecimalFormat;
/**
 *
 * @author 91822
 */
public class Choose_column extends javax.swing.JFrame {

    String line;
    String [][] values;
    int countrow;
    int countcol;
    double [] population;
    /**
     * Creates new form Choose_column
     */
    public Choose_column(Options a) {
        initComponents();
        this.values=a.getvalues();
        this.countrow=a.getcountrow();
        this.countcol=a.getcountcol();
        
    }
    
    public Choose_column()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        column_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        column_name.setText("Enter the column name whose parameter is to be estimated:");
        column_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                column_nameActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel1.setText("STATISTICAL ESTIMATION");

        jButton1.setText("CALCULATE\n");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(204, 204, 204))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(column_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jButton1)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(column_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void column_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_column_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_column_nameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int column=0;
        line=column_name.getText();
        for(int j=0;j<countcol;j++)
        {
	      if(line.equals(values[0][j]))
	      {
		   column=j;
        	   break;
	      }
        }
				   
				   
        population=new double[countrow-2];
        for(int j=0;j<countrow-2;j++)
        {
	       population[j]=Double.parseDouble(values[j+1][column]);
        }
				   
				   
        this.Mean_estimation(population);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void Mean_estimation(double []population)
    {
        MaximumLikelihoodEstimate Mle=new MaximumLikelihoodEstimate(population);
	BayesianEstimate Bayesian_normal=new BayesianEstimate(population,"N");
	BayesianEstimate Bayesian_exp=new BayesianEstimate(population,"E");
		
	Bayesian_normal.setSample(Mle.getSample());
	Bayesian_exp.setSample(Mle.getSample());
	Mle.Estimate();
	Bayesian_normal.Estimate();
	Bayesian_exp.Estimate();
        
        DecimalFormat formatter=new DecimalFormat("#0.000");
		
       // System.out.println("\nMAXIMUM LIKELIHOOD ESTIMATION : "+Mle.getMaximumLikelihoodEstimation()+"\nBAYESIAN ESTIMATION (PRIOR NORMAL ) : "+Bayesian_normal.getBayesianEstimation()+"\nBAYESIAN ESTIMATION (PRIOR EXPONENTIAL) : "+Bayesian_exp.getBayesianEstimation()+"\nORIGINAL POPULATION MEAN : "+Mle.getPopulation_mean());

	JOptionPane.showMessageDialog(null,"\nMAXIMUM LIKELIHOOD ESTIMATION : "+formatter.format(Mle.getMaximumLikelihoodEstimation())+"\nBAYESIAN ESTIMATION (PRIOR NORMAL ) : "+formatter.format(Bayesian_normal.getBayesianEstimation())+"\nMAP ESTIMATION (PRIOR EXPONENTIAL) : "+formatter.format(Bayesian_exp.getBayesianEstimation())+"\nORIGINAL POPULATION MEAN : "+formatter.format(Mle.getPopulation_mean()));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Choose_column.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Choose_column.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Choose_column.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Choose_column.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Choose_column().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField column_name;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
